version: '3.9'

x-environment:
  &py-environment
  DEBUG: 'False'
  NODE_ENV: 'production'
  DEV_ENV: 'True'  # necessary to have nginx connect to web container
  SECRET_KEY: local_unsafe_key
  DATABASE_URL: postgres://postgres@db:5432/postgres
  MITX_ONLINE_BASE_URL: ${MITX_ONLINE_BASE_URL:-http://mitxonline.odl.local:8013}
  MITX_ONLINE_SECURE_SSL_REDIRECT: 'False'
  MITX_ONLINE_DB_DISABLE_SSL: 'True'
  MITX_ONLINE_ADMIN_EMAIL: admin@localhost
  ELASTICSEARCH_URL: elastic:9200
  CELERY_TASK_ALWAYS_EAGER: 'False'
  REDIS_URL: redis://redis:6379/4
  DOCKER_HOST: ${DOCKER_HOST:-missing}
  WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
  WEBPACK_DEV_SERVER_PORT: ${WEBPACK_DEV_SERVER_PORT:-8012}
  WEBPACK_USE_DEV_SERVER: 'True'
  OPENEDX_API_KEY: ${OPENEDX_API_KEY:-PUT_YOUR_API_KEY_HERE}

x-extra-hosts:
  &default-extra-hosts
  - "edx.odl.local:${OPENEDX_IP:-172.22.0.1}"
  - "host.docker.internal:host-gateway"

services:
  db:
    image: postgres:11.6
    ports:
      - "5432"

  redis:
    image: redis:6.0.5
    ports:
      - "6379"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8013:8013"
    links:
      - web
    volumes:
      - ./config/nginx.conf.erb:/etc/nginx/templates/nginx.conf.erb
      - ./:/app
    environment:
      NGINX_WORKERS: 1
      PORT: 8013
      NGINX_UWSGI_PASS: "web:8011"
    networks:
      default:
        aliases:
          # this ensures that containers route this hostname back to the web app
          - "mitxonline.odl.local"
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: django-server
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate --noinput &&
      python3 manage.py configure_wagtail &&
      uwsgi uwsgi.ini --honour-stdin'
    stdin_open: true
    tty: true
    ports:
      - "8011:8011"
    environment:
      << : *py-environment
      PORT: 8011
    env_file: .env
    links:
      - db
      - redis
    volumes:
      - .:/app
      - django_media:/var/media
    extra_hosts: *default-extra-hosts

  watch:
    image: node:17.8
    working_dir: /app
    command: >
      /bin/bash -c './frontend/public/webpack_dev_server.sh --install'
    ports:
      - "8012:8012"
    environment:
      NODE_ENV: 'development'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      CONTAINER_NAME: 'watch'
      WEBPACK_HOST: 0.0.0.0
      WEBPACK_PORT: 8012
    env_file: .env
    volumes:
      - .:/app
      - yarn-cache:/home/mitodl/.cache/yarn

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      target: django
    environment: *py-environment
    env_file: .env
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A main.celery:app worker -B -l ${MITX_ONLINE_LOG_LEVEL:-INFO}'
    links:
      - db
      - redis
    volumes:
      - .:/app
      - django_media:/var/media
    extra_hosts: *default-extra-hosts

  refine:
    image: node:17.8
    working_dir: /app
    command: sh -c 'yarn install --immutable && yarn workspace mitx-online-staff-dashboard run dev'
    ports:
       - "8016:8016"
    environment:
      PORT: 8016
      REACT_APP_OIDC_CONFIG_AUTHORITY: ${MITX_ONLINE_BASE_URL:-http://mitxonline.odl.local:8013}/oauth2/
      REACT_APP_OIDC_CONFIG_CLIENT_ID: ${MITX_ONLINE_ADMIN_CLIENT_ID:-refine-local-client-id}
      REACT_APP_OIDC_CONFIG_REDIRECT_URI: ${MITX_ONLINE_ADMIN_BASE_URL:-http://mitxonline.odl.local:8016}/oauth2/login/
      REACT_APP_MITX_ONLINE_DATASOURCE: ${MITX_ONLINE_BASE_URL:-http://mitxonline.odl.local:8013}/api
    volumes:
      - .:/app
      - npm-cache:/root/.npm

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter-notebook
    profiles: ["notebook"]
    volumes:
      - .:/app
    environment:
      << : *py-environment
    env_file: .env
    command: >
      /bin/bash -c '
      sleep 3 &&
      jupyter notebook --no-browser --ip=0.0.0.0 --port=8080'
    ports:
      - "8080:8080"

volumes:
  npm-cache: {}
  django_media: {}
  yarn-cache: {}