# Generated by Django 3.2.18 on 2023-07-24 19:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cms', '0027_wagtail_v5_upgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InstructorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('instructor_name', models.CharField(blank=True, default='Tristan Doe', help_text="The instructor's name.", max_length=255, null=True)),
                ('instructor_title', models.CharField(blank=True, default='Scholar', help_text="The instructor's title.", max_length=255, null=True)),
                ('short_bio', wagtail.fields.RichTextField(blank=True, help_text='A short bio, used in the card shown in a Meet Your Instructors section.', null=True)),
                ('application_denied_text', wagtail.fields.RichTextField(blank=True, help_text='A longer bio.', null=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text="Upload the instructor's featured image (typically a headshot).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
