name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.6
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

      redis:
        image: redis:5.0.8
        ports:
          - 6379:6379

      elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        env:
          network.host: "0.0.0.0"
          http.cors.enabled: "true"
          http.cors.allow-origin: "*"
          rest.action.multi.allow_explicit_index: "false"
          ES_JAVA_OPTS: -Xms512m -Xmx512m"
        ports:
          - 9200:9200

    steps:
      - uses: actions/checkout@v2

      - name: Apt update
        run: sudo apt-get update -y

      - name: Apt install
        run: cat Aptfile | sudo xargs apt-get install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.5"

      - id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/test_requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt -r test_requirements.txt

      # disabled for now because it's broken for some reason
      # - name: Lint
      #   run: pylint ./**/*.py
        
      - name: Code Formatting (Black)
        run: black --check .

      # Configurations required for elasticsearch.
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 6.7.1

      - name: Running Celery
        run: |
          celery -A main worker -B -l INFO &
          sleep 10
        env:
          CELERY_TASK_ALWAYS_EAGER: 'True'
          CELERY_BROKER_URL: redis://localhost:6379/4
          CELERY_RESULT_BACKEND: redis://localhost:6379/4
          SECRET_KEY: local_unsafe_key
          MITX_ONLINE_BASE_URL: http://localhost:8013
          MAILGUN_SENDER_DOMAIN: other.fake.site
          MAILGUN_KEY: fake_mailgun_key
          MITX_ONLINE_ADMIN_EMAIL: example@localhost
          OPENEDX_API_CLIENT_ID: fake_client_id
          OPENEDX_API_CLIENT_SECRET: fake_client_secret
          OPENEDX_API_KEY: test-openedx-api-key

      - name: Tests
        run: |
          export MEDIA_ROOT="$(mktemp -d)"
          ./scripts/test/python_tests.sh
        env:
          DEBUG: False
          NODE_ENV: 'production'
          CELERY_TASK_ALWAYS_EAGER: 'True'
          CELERY_BROKER_URL: redis://localhost:6379/4
          CELERY_RESULT_BACKEND: redis://localhost:6379/4
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          DISABLE_WEBPACK_LOADER_STATS: 'True'
          ELASTICSEARCH_URL: localhost:9200
          MAILGUN_KEY: fake_mailgun_key
          MAILGUN_SENDER_DOMAIN: other.fake.site
          MITX_ONLINE_ADMIN_EMAIL: example@localhost
          MITX_ONLINE_BASE_URL: http://localhost:8013
          MITX_ONLINE_DB_DISABLE_SSL: 'True'
          MITX_ONLINE_EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
          MITX_ONLINE_NOTIFICATION_EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
          MITX_ONLINE_SECURE_SSL_REDIRECT: 'False'
          MITX_ONLINE_USE_S3: 'False'
          OPENEDX_API_BASE_URL: http://localhost:18000
          OPENEDX_API_CLIENT_ID: fake_client_id
          OPENEDX_API_CLIENT_SECRET: fake_client_secret
          OPENEDX_API_KEY: test-openedx-api-key
          SECRET_KEY: local_unsafe_key

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 15.14.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lints
        run: npm run lint

      - name: Code formatting
        run: npm run fmt:check

      - name: Scss lint
        run: npm run scss_lint

      - name: Flow
        run: npm run flow

      - name: Tests
        run: npm run test
        env:
          CODECOV: true
          NODE_ENV: development

      - name: Webpack build
        run: node node_modules/webpack/bin/webpack.js --config webpack.config.prod.js --bail

      - name: Upload test coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
